# Generated by Django 3.2.4 on 2021-06-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombreCategoria',
            field=models.CharField(max_length=40, verbose_name='nombre categoria'),
        ),
    ]
