# Generated by Django 3.2.4 on 2021-06-20 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaWeb', '0002_alter_categoria_nombrecategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionArte',
            fields=[
                ('Nombre', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patente')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca vehiculo')),
                ('modelo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Modelo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaWeb.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='vehiculo',
        ),
    ]
