# Generated by Django 3.2.4 on 2021-06-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaWeb', '0003_auto_20210620_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacionarte',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='publicacionarte',
            name='modelo',
        ),
        migrations.AddField(
            model_name='publicacionarte',
            name='apellido',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='apellido'),
        ),
        migrations.AddField(
            model_name='publicacionarte',
            name='correo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='correo'),
        ),
        migrations.AddField(
            model_name='publicacionarte',
            name='descObra',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Desc Obra'),
        ),
        migrations.AddField(
            model_name='publicacionarte',
            name='nombreObra',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre Obra'),
        ),
        migrations.AlterField(
            model_name='publicacionarte',
            name='Nombre',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='nombre'),
        ),
    ]
