# Generated by Django 3.2.4 on 2021-06-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaWeb', '0004_auto_20210620_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacionarte',
            name='imagenPublicacion',
            field=models.ImageField(null=True, upload_to='fotopublicaciones'),
        ),
        migrations.AlterField(
            model_name='publicacionarte',
            name='descObra',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DescObra'),
        ),
        migrations.AlterField(
            model_name='publicacionarte',
            name='nombreObra',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NombreObra'),
        ),
    ]
