# Generated by Django 3.2.4 on 2021-06-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaWeb', '0007_alter_publicacionarte_imagenpublicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionarte',
            name='imagenPublicacion',
            field=models.ImageField(null=True, upload_to='fotopublicaciones', verbose_name='imagen'),
        ),
    ]
