# Generated by Django 3.2.4 on 2021-07-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaWeb', '0009_auto_20210629_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionarte',
            name='imagenPublicacion',
            field=models.ImageField(blank=True, null=True, upload_to='fotopublicaciones', verbose_name='imagen'),
        ),
    ]
